# Generated by Django 5.2.4 on 2025-07-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_demandeur', models.CharField(max_length=100)),
                ('nom_patient', models.CharField(max_length=100)),
                ('telephone_demandeur', models.CharField(max_length=8)),
                ('genre_patient', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], max_length=50)),
                ('adresse_patient', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('type_analyse', models.CharField(max_length=200)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('equipement', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('reactif_consommable', models.CharField(blank=True, max_length=100)),
                ('cout', models.FloatField(blank=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('duree_type', models.CharField(blank=True, choices=[('jour', 'Jour'), ('heure', 'Heure')], default='jour', max_length=5)),
                ('duree', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('quantite', models.IntegerField()),
                ('recommended_quntite', models.IntegerField()),
                ('mesure_unite', models.CharField(choices=[('mg', 'mg'), ('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l')], default='mg', max_length=20)),
                ('categorie', models.CharField(choices=[('reactif', 'Reactif'), ('consommable', 'Consommable')], default='reactif', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=300)),
                ('adresse', models.CharField(max_length=200)),
                ('numero_identification', models.CharField(max_length=20, unique=True)),
                ('longitude', models.FloatField()),
                ('laltitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('recepteur_telephone', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nni', models.CharField(max_length=10, unique=True)),
                ('nom_complet', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('telephone', models.CharField(max_length=8, unique=True)),
                ('adresse', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], max_length=10)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('responsable_stock', 'Responsable de Stock'), ('specialiste', 'Specialiste'), ('technicien_labo', 'Technicien de Labo'), ('caissier', 'Caissier')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('analyse_associed', models.ManyToManyField(blank=True, related_name='specialites', to='laboratoireapp.analyse')),
            ],
        ),
    ]
