# Generated by Django 5.2.4 on 2025-07-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoireapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse',
            name='cout',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
