# Generated by Django 5.2.4 on 2025-07-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoireapp', '0002_alter_analyse_cout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse',
            name='cout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
