# Generated by Django 5.2.4 on 2025-07-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoireapp', '0003_alter_analyse_cout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse',
            name='duree',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
