# Generated by Django 5.2.4 on 2025-07-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoireapp', '0004_alter_analyse_duree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
