# Generated by Django 5.2.4 on 2025-07-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoireapp', '0005_alter_analyse_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialiteAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='specialite',
            name='analyse_associed',
            field=models.ManyToManyField(to='laboratoireapp.specialiteanalyse'),
        ),
    ]
