# Generated by Django 5.2.4 on 2025-07-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoireapp', '0006_specialiteanalyse_alter_specialite_analyse_associed'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='analyses_autorises',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs', to='laboratoireapp.specialiteanalyse'),
        ),
        migrations.AlterField(
            model_name='specialite',
            name='analyse_associed',
            field=models.ManyToManyField(blank=True, related_name='specialites', to='laboratoireapp.specialiteanalyse'),
        ),
    ]
