# Generated by Django 5.2.4 on 2025-07-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoireapp', '0007_utilisateur_analyses_autorises_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('responsable_stock', 'Responsable de Stock'), ('specialiste', 'Specialiste')], max_length=50),
        ),
    ]
